services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job-portal-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    ports:
      - "8000:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=job-portal
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db
    networks:
      - job-portal-network

  db:
    image: mysql:8.0
    container_name: job-portal-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: job-portal
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - job-portal-network

networks:
  job-portal-network:
    driver: bridge

volumes:
  db_data:
